### ISSUE TITLE
wareki-0.1.1 permission is 640

### ISSUE THREAD

**Issue by mnmemo** [sugi/wareki#1]
gem 'wareki' でインストールしたところ
ファイルのパーミッションが640になっていまして
別のユーザーが使うと読み込み権限がなくLoadErrorが起きてしまいます。

gem 'wareki', github: 'sugi/wareki' でgithubからインストールすると使えました。

**Comment by sugi** [comment]
おっとすみません。
変更して更新しておきます。

**Comment by sugi** [comment]
0.1.2 で修正しておきました。
指摘ありがとうございました。
