### ISSUE TITLE
上旬、中旬、下旬というふうに日付をパースできるようになってほしい

### ISSUE THREAD

**Issue by kaikaiikkun** [sugi/wareki#18]
04/20→4月中旬　というふうにパースされるようにしてほしい。

1〜10日→上旬
11〜20日→中旬
21〜31日→下旬

**Comment by sugi** [comment]
> 04/20→4月中旬
だとすると、パースではなくてフォーマットでしょうか？

仮にフォーマット文字列が `%Z` だとして、

```ruby
puts Date.parse('2022-04-03').strftime('%m月%Z')
```

で

```
4月上旬
```

になってほしい、ということであっていますか？

フォーマット文字列を追加すること自体は別に簡単なんですが、英語でも early/mid/late に相当するフォーマット文字列がないのと、自力でその場で書くのはすごい手軽な内容なので、ちょっとフォーマット文字列を足すのに躊躇するところです。

**Comment by kaikaiikkun** [comment]
こちら返信していただいていたのに気づけず申し訳ありません！
あったらいいな程度で起票させていただきました。

欲しかったものはコメントいただいた通りのものです。
確かに簡単なものだったので、自分でstrftimeを拡張して対応しました。
