### ISSUE TITLE
Wrong result ?

### ISSUE THREAD

**Issue by trois** [sugi/wareki#2]
wareki (0.1.2)
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]

Date.parse("1989/1/7"  ).strftime('%JF')
  Wareki::UnsupportedDateRange: Cannot find era for date 2447534
  from /Users/me/Documents/program/WS/ruby_etc/gengou/vendor/bundle/gems/wareki-0.1.2/lib/wareki/date.rb:60:in `jd'

Date.parse("1912/7/29" ).strftime('%JF')
  Wareki::UnsupportedDateRange: Cannot find era for date 2419613
  from /Users/me/Documents/program/WS/ruby_etc/gengou/vendor/bundle/gems/wareki-0.1.2/lib/wareki/date.rb:60:in `jd'

Date.parse("1926/12/24").strftime('%JF')
  Wareki::UnsupportedDateRange: Cannot find era for date 2424874
  from /Users/me/Documents/program/WS/ruby_etc/gengou/vendor/bundle/gems/wareki-0.1.2/lib/wareki/date.rb:60:in `jd'

Date.parse("1868/1/24" ).strftime('%JF') 
=> "慶応四年月九千九百九十九京九千九百九十九兆九千九百九十九億九千九百九十九万九千六百四十六日"
'

**Comment by sugi** [comment]
Ouch, thank you very much!
It's a issue of handling last days of era and year.
I'll fix that.

**Comment by sugi** [comment]
Fixed with 0.1.3.

Thank you for reporting!

**Comment by trois** [comment]
thank you(^o^)
